-- AlterTable
ALTER TABLE `notification` MODIFY `type` ENUM('PROFILE_UPDATED', 'NEW_EMPLOYEE_ADDED', 'ANNOUNCEMENT', 'PASSWORD_CHANGE', 'ROLE_CHANGE') NOT NULL;

-- AlterTable
ALTER TABLE `notificationtemplate` MODIFY `type` ENUM('PROFILE_UPDATED', 'NEW_EMPLOYEE_ADDED', 'ANNOUNCEMENT', 'PASSWORD_CHANGE', 'ROLE_CHANGE') NOT NULL;
